
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: "/util-presentation"
url: "https://sara-sabr.github.io/"

# Build settings
markdown: kramdown
include: ["_pages"]
exclude: ["wip-tec", "CONTRIBUTING.md", "cspell.json", "LICENSE", "link-check.js", "package.json", "package-lock.json", "README.md"]

# i18n
description:
  en: This is a tool to host markdown presentations for the Strategy, Architecture and Business Relationship Directorate.
  fr: Ceci est un outil pour héberger des présentations "markdown" pour le directorat Stratégie, Architecture et Relations d'affaires.
home:
  en: Home
  fr: Accueil
index:
  en: home.html
  fr: accueil.html
language:
  en: English
  fr: Français
title:
  en: SABR Presentation Utility
  fr: Utilitaire de présentation SARA
viewOnGithub:
  en: View on GitHub
  fr: Voir sur GitHub
writtenBy:
  en: Written by
  fr: Écrit par
lastModified:
  en: Last modified
  fr: Dernière modification
blogPosts:
  en: Our Blog Posts
  fr: Nos Billets
notice:
  en: All work found on this site are ideas and proposals from the IT Strategy team within ESDC. Content here does not represent the official stance of ESDC nor the Government of Canada at large.
  fr: Tous les travaux présentés sur ce site sont des idées et des propositions de l'équipe de la stratégie informatique de EDSC. Le contenu présenté ici ne représente pas la position officielle de EDSC ni celle du gouvernement du Canada en général.
